### ISSUE TITLE
When an IP has no Reverse DNS set, it will say it's valid

### ISSUE THREAD

**Issue by xvilo** [kalmargabor/crawler-check#3]
An example IP we're having issues with is `83.220.237.226`. 

When the following code is executed:
```
$host = gethostbyaddr($ip);
$ipAfterLookup = gethostbyname($host);

die(var_dump($host, $ipAfterLookup));
```

This will return 
```
string(14) "83.220.237.226"
string(14) "83.220.237.226"
```

We could a early return if both values are identical. The `endsWith` method is flawed because for this IP they have an identical length `83.220.237.226` (14) and `.googlebot.com` (14)

**Comment by xvilo** [comment]
Made a fix with: https://github.com/kalmargabor/crawler-check/pull/4

**Comment by kalmargabor** [comment]
Thank you!
